export const ConstantsLib = {
  FULL_NAME: 'Full name',
  NOMINATED_FULL_NAME: 'Nominated full name',
  DATE_OF_BIRTH: '11/11/1985',
  ALTERNATIVE_DATE_OF_BIRTH: '30/03/1970',
  SOMEONE_ELSE_DATE_OF_BIRTH: '30/03/2020',
  COLLECTION_DATE: '01/01/2010',
  BRP_COLLECTION_DATE: '11/05/2015',
  BRP_LOST_DATE: '11/08/2015',
  NATIONALITY: 'Ireland',
  ALTERNATIVE_NATIONALITY: 'Italy',
  PASSPORT_NUMBER: 'RZ1000452',
  COLLECTION_PASSPORT_NUMBER: '04D006389',
  BRP_NUMBER: 'RZ1000452',
  EMAIL: 'sas-test@test.com',
  PHONE: '07900000000',
  HOUSE_NUMBER: '1',
  STREET: 'Test Street',
  TOWN: 'Croydon',
  COUNTY: 'Surrey',
  POSTCODE: 'CR0 2EU',
  CASE_ID: '123456',
  TRACKING_NUMBER: 'AA123456789GB',
  SITUATION: 'hi',
  FAMILY_NAME: 'Barbara',
  GIVEN_NAME: 'Sara',
  SPONSOR_REFERENCE: '1234567',
  SIGNATURE_DETAILS: 'Italian sign',
  PHOTOGRAPH_DETAILS: 'mistake',
  NATIONAL_INSURANCE_NUMBER: '123reedf',
  DAMAGED_BRP_DETAILS: '123reedf',
  PROBLEM_DETAILS: 'reason',
  DELIVERY_DETAILS: 'Use the address on the letter',
  UNKNOWN_POST_OFFICE_DETAILS: "I don't know which Post Office",
  UNDER_18_COLLECTION_DETAILS: 'Under 18 attempted collection',
  IDENTITY_PROBLEM_DETAILS: 'Could not prove identity',
  OTHER_COLLECTOR_DETAILS: 'Someone else attempted collection',
  VIGNETTE_PROBLEM_DETAILS: 'Vignette not linked to family',
  LOST_PASSPORT_DETAILS: 'Lost passport',
  YES_OPTION: 'yes',
  NO_OPTION: 'no',
  POST_OFFICE_OPTION: 'Post Office',
  SPONSOR_OPTION: 'Sponsor',
  BRP_CARD_OPTION: 'brp-card',
  PASSPORT_OPTION: 'passport',
  FEMALE_OPTION: 'Female',
  UNKNOWN_POST_OFFICE_OPTION: 'which-post-office',
  UNDER_18_OPTION: 'under-age',
  IDENTITY_PROBLEM_OPTION: 'non-identity',
  OTHER_COLLECTOR_OPTION: 'others-identity',
  VIGNETTE_PROBLEM_OPTION: 'passport-family',
  LOST_PASSPORT_OPTION: 'passport-lost',
  NO_BRP_OPTION: 'no-brp',
  INCAPABLE_OPTION: 'incapable',
  PROBLEM_FAMILY_NAME: 'Family name',
  PROBLEM_GIVEN_NAME: 'Given name(s)',
  PROBLEM_PLACE_OF_BIRTH: 'Place of birth',
  PROBLEM_DATE_OF_BIRTH: 'Date of birth',
  PROBLEM_GENDER: 'Gender',
  PROBLEM_SPONSOR_REFERENCE: 'Sponsor reference',
  PROBLEM_NATIONALITY: 'Nationality',
  PROBLEM_SIGNATURE: 'Signature',
  PROBLEM_PHOTOGRAPH: 'Photograph',
  PROBLEM_NATIONAL_INSURANCE: 'National Insurance number',
  PROBLEM_DAMAGED_BRP: 'Faulty or damaged BRP',
  PROBLEM_CONDITIONS: 'Conditions',
  PROBLEM_LENGTH_OF_STAY: 'Length of stay',
  PROBLEM_BIOGRAPHICS: 'Biographics',
  PROBLEM_BRP_NOT_WORKING: "My BRP doesn't work",
  COLLECTION_REASON_UNKNOWN_POST_OFFICE: "I don't know which Post Office I need to collect my BRP from",
  COLLECTION_REASON_UNDER_18: 'I am under 18 and attempted collection without my responsible adult',
  COLLECTION_REASON_IDENTITY: 'I could not prove my identity',
  COLLECTION_REASON_OTHER_PERSON: 'Someone attempted to collect my BRP on my behalf, but was unable to',
  COLLECTION_REASON_VIGNETTE: 'The vignette (sticker) in my passport is not linked to my family',
  COLLECTION_REASON_LOST_PASSPORT: 'I have lost my passport',
  COLLECTION_REASON_NO_BRP: 'My BRP was not there',
  UK_ROUTE: 'UK',
  OUTSIDE_UK_ROUTE: 'Outside UK',
  MEDICAL_HELP_REASON: 'Medical help',
  UNDER_18_REASON: 'Under 18',
  NOT_DELIVERED_WITH_TRACKING: {
    hasTrackingNumber: true,
    hasHomeOfficeLetter: false,
  },
  NOT_DELIVERED_WITHOUT_TRACKING: {
    hasTrackingNumber: false,
    hasHomeOfficeLetter: true,
  },
  REPORT_PROBLEM_FAMILY_NAME: {
    whereApplied: 'UK',
    problem: 'Family name',
    answerAddressQuestionWithYes: true,
  },
  REPORT_PROBLEM_GIVEN_NAME: {
    whereApplied: 'UK',
    problem: 'Given name(s)',
    answerAddressQuestionWithYes: false,
  },
  REPORT_PROBLEM_PLACE_OF_BIRTH: {
    whereApplied: 'Outside UK',
    problem: 'Place of birth',
    answerAddressQuestionWithYes: true,
  },
  REPORT_PROBLEM_DATE_OF_BIRTH: {
    whereApplied: 'Outside UK',
    problem: 'Date of birth',
    answerAddressQuestionWithYes: false,
  },
} as const;